# Generated by Django 5.0.6 on 2024-05-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='personal number'),
        ),
    ]
