# Generated by Django 5.0.6 on 2024-05-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_birth_date_alter_user_personal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.IntegerField(choices=[(1, 'Librarian'), (2, 'Borrower'), (3, 'Admin')], default=1, verbose_name='profile'),
        ),
    ]
