# Generated by Django 5.0.6 on 2024-05-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='library.book', verbose_name='Book'),
        ),
    ]
