# Generated by Django 5.0.6 on 2024-05-16 18:23

import django.db.models.deletion
import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_alter_book_author_alter_book_genre'),
        ('users', '0002_alter_user_birth_date_alter_user_personal_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateField(verbose_name='checkout date')),
                ('due_date', models.DateField(default=transactions.models.get_default_due_date, verbose_name='due date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='return date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='library.book', verbose_name='book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.borrower', verbose_name='borrower')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-checkout_date'],
            },
        ),
    ]
