# Generated by Django 5.0.6 on 2024-05-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_alter_book_author_alter_book_genre'),
        ('transactions', '0002_initial'),
        ('users', '0002_alter_user_birth_date_alter_user_personal_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('book', 'borrower')},
        ),
    ]
