# Generated by Django 5.0.6 on 2024-05-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checkout_date',
            field=models.DateField(auto_now_add=True, verbose_name='checkout date'),
        ),
    ]
